#!/bin/bash
#Made by Sadiq Saif <sadiq@asininetech.com>
#Purpose: Installs UnityOne icon
#License: Do whatever you want with this script, just keep this license intact.


if  [[ "$(/usr/bin/whoami)" != "root" ]]; then
	sudo -p "Enter your admin password: " cp $HOME/UnityOne/ubuntuoneup.png /usr/share/icons
	sudo -k
else
	cp $HOME/UnityOne/ubuntuoneup.png /usr/share/icons
fi
